services:
  n8n:
    image: docker.n8n.io/n8nio/n8n:latest
    container_name: n8n
    restart: unless-stopped
    ports:
      - "5678:5678"
    environment:
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - NODE_ENV=production
      - GENERIC_TIMEZONE=America/Lima
      - TZ=America/Lima
    volumes:
      - n8n_data:/home/node/.n8n
      - ./workflows:/workflows:ro
    # Importa automáticamente todos los workflows de /workflows antes de iniciar el servidor n8n
    command: /bin/sh -c "n8n import:workflow --separate=/workflows ; n8n start"

volumes:
  n8n_data:
